<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\RemoteProtocol\RemoteProtocol.csproj" />
    <None Include="..\..\..\..\protocol\testdata\v1.json"
          Link="testdata\v1.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\..\protocol\testdata\auth-v1.json"
          Link="testdata\auth-v1.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\..\protocol\testdata\tls-v1.json"
          Link="testdata\tls-v1.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
